version: 2.1

# orbs:
  
# commands:
  
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - run: npm run link
  test:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - run: npm run test
  
  analyze:
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - checkout
      - run: npm run audit

workflows:
  exercise_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test


  